import './globals.css';
import { HeaderComponent } from '@/components/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="pt-16">
        <HeaderComponent />
        {children}
      </body>
    </html>
  )
}
